spring.application.name=image-storage-service
server.port=8088

minio.bucket-name=${BUCKET_NAME}
minio.user=${MINIO_ROOT_USER}
minio.password=${MINIO_ROOT_PASSWORD}
minio.access-key=${MINIO_ACCESS_KEY}
minio.secret-key=${MINIO_SECRET_KEY}

minio.endpoint=${MINIO_ENDPOINT}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
