spring.application.name=text-moderation-service
server.port=8092
spring.main.web-application-type=none

spring.config.import=optional:file:.env[.properties]

spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.chat.options.temperature=0

spring.rabbitmq.host=message-broker
spring.rabbitmq.port=5672
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.simple.possible-authentication-failure-fatal=false
spring.rabbitmq.listener.simple.declaration-retries=20
spring.rabbitmq.listener.simple.failed-declaration-retry-interval=5s
